name = "apis-data-spcdeinfoservice"
main = "src/index.js"
workers_dev = true
compatibility_date = "2025-04-15"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = false

  [observability.logs]
  enabled = true
  head_sampling_rate = 1
  invocation_logs = true
